{% set version = "1.1.1" %}

package:
  name: ossindex-lib
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/ossindex-lib/ossindex-lib-{{ version }}.tar.gz
  sha256: 06eff2263a067aceee8fb45e11300c7d80863c5e9bb13016b866df40b30fe9eb

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -c "__import__('os').unlink('pyproject.toml')"
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
  run:
    - importlib-metadata >=3.4
    - packageurl-python >=0.9.0,<0.10.0
    - python >=3.6,<4.0
    - pyyaml >=5.4.1
    - requests >=2.20.0,<3.0.0
    - tinydb >=4.5.0,<5.0.0
    - types-pyyaml >=5.4.1,<6.0.0
    - types-requests >=2.25.1,<3.0.0
    - types-setuptools >=57.0.0

test:
  imports:
    - ossindex
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sonatype-nexus-community/ossindex-python
  summary: A library for querying the OSS Index free catalogue of open source components to help developers identify vulnerabilities, understand risk, and keep their software safe.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
